name: kitchen
description: A new Flutter application.

version: 0.0.8+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+3
  socket_io_client: ^0.9.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  date_format: ^1.0.8

#  adhara_socket_io: ^0.4.1
  http: ^0.12.0+4

flutter:
  #  plugin:
  #    platforms:
  #      android:
  #        package: com.infitio.adharasocketio
  #        pluginClass: AdharaSocketIoPlugin

  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600